#!/bin/bash

cd ./api
composer install
cd ../

cd ./employee-app
yarn
yarn build
cd ../

cd ./employer-dashboard
yarn
yarn build
cd ../

[ -d ./dist ] && rm -rf ./dist
mkdir ./dist
cp -R ./api ./dist/api
cp -R ./employee-app/build ./dist/employee-app
cp -R ./employer-dashboard/build ./dist/employer-dashboard
